Repository enflujo/imagina-vacs, pull requests merged in 2023-08, with the labels that each got.

#69 📈 Agregar gráfica aces y datos a historia 2
  src/componentes/graficas/proyecto2/Grafica1.astro
  src/datos/p2Aces.ts
  src/datos/p2ConductasRiesgo.ts
  src/pages/proyecto2.astro
Labels: front-end :art:

#78 ✨ Agregar historia 4
  recursos/iconos/flor_2.svg
  src/pages/proyecto4.astro
  src/utilidades/constantes.ts
Labels: front-end :art:

#79 ✨ Agregar cierre a historia 2
  src/pages/proyecto2.astro
Labels: front-end :art:

#73 👀 algunos ajustes a las clases
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#76 📈 Puntos porcentuales
  astro.config.mjs
  package.json
  src/componentes/Colombina.astro
  src/componentes/PuntosPorcentuales.astro
  src/componentes/graficas/proyecto2/Grafica2.astro
  src/datos/p2ConductasRiesgo.ts
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/plantillas/Plantilla.astro
  src/scss/estilosGlobales.scss
  yarn.lock
Labels: front-end :art:

#80 Graficas historia 1
  src/componentes/graficas/proyecto1/Grafica2.astro
  src/datos/migracionViolenciaPdet.ts
  src/pages/proyecto1.astro
Labels: front-end :art:

#84 🤡 experimentos y ajustes
  src/scss/_diagramacion.scss
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#89 🐛Corrección de detalles de historia 1
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/scss/_diagramacion.scss
Labels: bicho :bug:

#91 💥 detallitos de diseño
  src/componentes/Menu.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#90 📈 Graficas historia 3 Parte I
  src/componentes/Colombina.astro
  src/componentes/Torta.astro
  src/componentes/graficas/proyecto1/Grafica1.astro
  src/componentes/graficas/proyecto3/Grafica1.astro
  src/componentes/graficas/proyecto3/Grafica2.astro
  src/componentes/graficas/proyecto3/Grafica3.astro
  src/datos/p3AgresionSexualConocidos.ts
  src/datos/p3AgresionSexualEdad.ts
  src/datos/p3ViolenciaPorGenero.ts
  src/pages/proyecto3.astro
Labels: front-end :art:

#92 🤺 Agregar elemento gráfica de personitas
  src/componentes/Personitas.astro
  src/componentes/graficas/proyecto1/Grafica2.astro
  src/datos/migracionViolenciaPdet.ts
  src/pages/proyecto1.astro
Labels: front-end :art:
