Repository enflujo/imagina-vacs, pull requests merged in 2023-07, with the labels that each got.

#5 🚧 Lectura erratas sugerencias
  src/pages/index.astro
Labels: front-end :art:

#20 🔪 Pasar todos los textos de los relatos a 1 columna
  src/componentes/NavegadorProyectos.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/pages/proyecto4.astro
  src/scss/estilosGlobales.scss
Labels: front-end :art:, optimización :zap:

#25 💄 Tipografías y colores
  src/fuentes/Nohemi-VF.ttf
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/scss/_constantes.scss
  src/scss/estilosGlobales.scss
Labels: front-end :art:

#28 🧷 incluir Blinker en main y en estilos
  src/fuentes/Blinker_variable_font.ttf
  src/pages/proyecto1.astro
Labels: ui :ocean:

#31 🐛 colores y cambio de fondo (falta el gradiente)
  src/scss/_constantes.scss
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#33 Estilos v1
  recursos/iconos/flecha.svg
  src/ambages/aparicionRelato.ts
  src/componentes/Menu.astro
  src/componentes/NavegadorProyectos.astro
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/scss/_constantes.scss
  src/scss/_diagramacion.scss
  src/scss/_normalizar.scss
  src/scss/componentes/_desliza.scss
  src/scss/estilosGlobales.scss
  src/utilidades/constantes.ts
Labels: front-end :art:

#37 🧱componente Glosario
  src/componentes/Glosario.astro
  src/pages/index.astro
Labels: front-end :art:

#45 📖 Glosario
  src/componentes/Glosario.astro
  src/componentes/Menu.astro
  src/pages/index.astro
  src/plantillas/Plantilla.astro
  src/scss/estilosGlobales.scss
Labels: front-end :art:, ui :ocean:

#58 ✨ Agregar componente Créditos
  src/componentes/Creditos.astro
  src/componentes/Desplegable.astro
  src/componentes/Glosario.astro
  src/componentes/Menu.astro
  src/plantillas/Plantilla.astro
Labels: front-end :art:

#60 🐛 corregir error de mapa
  src/componentes/Glosario.astro
  src/componentes/Mapa.astro
Labels: bicho :bug:, front-end :art:

#59 🐛 Ajustes glosario con la estructura desplegable
  src/componentes/Desplegable.astro
  src/componentes/Glosario.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#64 📏 avances tamaños queries columna
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/scss/_diagramacion.scss
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#65 🚧 avances
  src/componentes/Desplegable.astro
  src/componentes/Glosario.astro
  src/pages/index.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:
