Repository enflujo/imagina-vacs, pull requests merged in 2023-09, with the labels that each got.

#97 👧🏽 ajustes de diseño 29 y 30 de agosto
  src/pages/index.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#98 👷 ajustes en *Recursos*
  src/pages/recursos.astro
Labels: ui :ocean:

#99 📝 ajustes en estilo y gráficas
  recursos/iconos/caratriste.svg
  recursos/iconos/casa_rellena_bien_2.svg
  recursos/iconos/casa_rellena_rota.svg
  recursos/iconos/nube_triste_2.svg
  recursos/iconos/sol_tranqui.svg
  recursos/iconos/sol_tranqui_.svg
  src/componentes/graficas/proyecto1/Puntos.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/pages/proyecto4.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#100 🐛 avances editoriales
  src/componentes/Glosario.astro
  src/componentes/Indice.astro
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/pages/proyecto4.astro
  src/scss/estilosGlobales.scss
  src/utilidades/constantes.ts
Labels: ui :ocean:

#102 🐛 avances en créditos
  src/componentes/Creditos.astro
  src/componentes/Desplegable.astro
  src/componentes/Glosario.astro
  src/scss/estilosGlobales.scss
Labels: ui :ocean:

#104 🚀 Ajustes 1,3,4, glosario.creditos.desple.index.
  src/componentes/Creditos.astro
  src/componentes/Desplegable.astro
  src/componentes/Glosario.astro
  src/componentes/graficas/proyecto1/Puntos.astro
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto3.astro
  src/pages/proyecto4.astro
Labels: ui :ocean:

#106 🔥 Quitar gráficas de las que no hay datos
  src/pages/proyecto1.astro
  src/pages/proyecto3.astro
Labels: bicho :bug:

#107 💅🏿 Arreglos css
  src/componentes/Indice.astro
  src/componentes/graficas/proyecto1/Puntos.astro
  src/pages/proyecto2.astro
  src/pages/proyecto3.astro
  src/scss/_diagramacion.scss
  src/scss/estilosGlobales.scss
Labels: bicho :bug:, front-end :art:

#108 ⚡️ correción editorial 1, 2, 3, 4 lista.
  src/componentes/Creditos.astro
  src/componentes/Glosario.astro
  src/pages/index.astro
  src/pages/proyecto1.astro
  src/pages/proyecto2.astro
Labels: ui :ocean:

#110 🐛 Corregir error en índice
  src/componentes/Indice.astro
  src/scss/estilosGlobales.scss
Labels: bicho :bug:, front-end :art:

#112 📝 Agregar encuesta
  src/componentes/Desplegable.astro
  src/componentes/Encuesta.astro
  src/componentes/Menu.astro
  src/componentes/Personitas.astro
  src/pages/index.astro
  src/pages/proyecto2.astro
  src/plantillas/Plantilla.astro
  src/scss/estilosGlobales.scss
Labels: front-end :art:

#111 🔥 Limpiar código html y css
  src/componentes/Indice.astro
  src/componentes/Menu.astro
  src/pages/index.astro
  src/pages/proyecto4.astro
  src/scss/estilosGlobales.scss
Labels: front-end :art:, mejora :ant:
